/**
 * Lumen2D — asset sources: the provenance half of the asset system.
 *
 * A published pack (`assets-library/packs/base/…`) answers "what art do I have?". Its source index
 * (`assets-library/sources/base/index.json`) answers the questions an editor has to answer before
 * shipping a game:
 *
 *  * **Where did this file come from?** — a [AssetSource.recipe], e.g. `DemoArt.playerSheet()` for
 *    generated art, or `Tilemap/tilemap_packed.png` inside `kenney_pixel-platformer.zip` for a
 *    vendored third-party kit.
 *  * **Under which licence?** — `CC0-1.0` today; the pack manifest, the per-file sidecar and this
 *    index always agree, because the library build writes all three from the same values.
 *  * **How was it imported?** — [AssetSource.importSettings] carries the tile grid, frame size or
 *    nine-patch insets the importer used, so the asset browser can re-slice or re-import it.
 *  * **Which upstream archive is it from?** — [AssetSourceArchive] records the archive name, its
 *    SHA-256 and its metrics, so a vendored source can be re-fetched and verified.
 *
 * The engine only *reads* these files (never writes: the library build is a desktop/CI tool), so
 * games and the Android editor can both show provenance offline.
 */
package dev.lumen2d.core.assets

import dev.lumen2d.core.platform.VirtualFileSystem
import dev.lumen2d.core.util.Json
import dev.lumen2d.core.util.str
import dev.lumen2d.core.util.int
import dev.lumen2d.core.util.mapList
import dev.lumen2d.core.util.obj
import dev.lumen2d.core.util.strList

/** Where a published library file came from. */
enum class AssetOrigin(val id: String, val label: String) {
    /** Rebuilt from an engine recipe: art code, tone generator or the built-in bitmap font. */
    GENERATED("generated", "Generated by the engine"),

    /** Copied out of a vendored third-party archive (see [AssetSourceArchive]). */
    IMPORTED("imported", "Imported from a source archive"),

    /** No provenance file: the asset predates the source index or was added by hand. */
    UNKNOWN("unknown", "Unknown source");

    companion object {
        fun fromId(id: String): AssetOrigin = entries.firstOrNull { it.id == id.lowercase() } ?: UNKNOWN
    }
}

/** One published file's provenance. */
class AssetSource(
    /** Path inside the pack, e.g. `sprites/player.png`. */
    val path: String,
    val recipe: String,
    val origin: AssetOrigin,
    val source: String,
    val license: String,
    val author: String,
    val importSettings: Map<String, Any?> = emptyMap(),
    val notes: String = "",
) {
    /** One-line human summary for the asset browser's detail pane. */
    fun describe(): String = when {
        recipe.isEmpty() -> origin.label
        origin == AssetOrigin.IMPORTED -> "Imported from $recipe (${source.ifEmpty { "archive" }})"
        else -> "$recipe → $path"
    }

    companion object {
        fun fromJson(data: Map<String, Any?>): AssetSource = AssetSource(
            path = data.str("path"),
            recipe = data.str("recipe"),
            origin = AssetOrigin.fromId(data.str("origin")),
            source = data.str("source"),
            license = data.str("license"),
            author = data.str("author"),
            importSettings = data.obj("importSettings") ?: emptyMap(),
            notes = data.str("notes"),
        )
    }
}

/** The vendored archive an imported pack was published from. */
class AssetSourceArchive(
    val packId: String,
    val name: String,
    val upstream: String,
    val license: String,
    val author: String,
    val archive: String,
    val archiveSha256: String,
    val tileWidth: Int,
    val tileHeight: Int,
    val spacing: Int,
    val sheetColumns: Int,
    val sheetRows: Int,
    val files: List<ArchiveFile> = emptyList(),
) {
    class ArchiveFile(val name: String, val bytes: Long, val sha256: String)

    val tileCount: Int get() = sheetColumns * sheetRows

    fun describe(): String =
        "$name — $license, ${tileWidth}x$tileHeight tiles, ${archive.ifEmpty { "archive" }}"

    companion object {
        fun fromJson(data: Map<String, Any?>): AssetSourceArchive = AssetSourceArchive(
            packId = data.str("id"),
            name = data.str("name"),
            upstream = data.str("upstream"),
            license = data.str("license"),
            author = data.str("author"),
            archive = data.str("archive"),
            archiveSha256 = data.str("archiveSha256"),
            tileWidth = data.int("tileWidth", 16),
            tileHeight = data.int("tileHeight", 16),
            spacing = data.int("spacing"),
            sheetColumns = data.int("sheetColumns"),
            sheetRows = data.int("sheetRows"),
            files = data.mapList("files").map {
                ArchiveFile(it.str("name"), it["bytes"]?.let { b -> (b as? Number)?.toLong() ?: 0L } ?: 0L, it.str("sha256"))
            },
        )
    }
}

/** Provenance for a single pack: every published file plus the archive it came from, if any. */
class PackSourceIndex(
    val packId: String,
    val name: String,
    val description: String,
    val license: String,
    val author: String,
    val files: List<AssetSource>,
    val archive: AssetSourceArchive? = null,
) {
    private val byPath = files.associateBy { it.path }

    val fileCount: Int get() = files.size
    val generatedCount: Int get() = files.count { it.origin == AssetOrigin.GENERATED }
    val importedCount: Int get() = files.count { it.origin == AssetOrigin.IMPORTED }

    /** Looks up provenance by pack-relative path (`sprites/player.png`) or bare file name. */
    fun sourceOf(path: String): AssetSource? =
        byPath[path] ?: byPath[path.trimStart('/')] ?: files.firstOrNull { it.path.endsWith("/$path") }

    fun recipes(): List<String> = files.map { it.recipe }.filter { it.isNotEmpty() }.distinct().sorted()

    companion object {
        fun fromJson(data: Map<String, Any?>): PackSourceIndex = PackSourceIndex(
            packId = data.str("pack"),
            name = data.str("name"),
            description = data.str("description"),
            license = data.str("license"),
            author = data.str("author"),
            files = data.mapList("files").map { AssetSource.fromJson(it) },
        )
    }
}

/**
 * Reads the source folders under `assets-library/sources/…`: one [PackSourceIndex] per published pack, one
 * [AssetSourceArchive] per vendored third-party source.
 */
class AssetSourceIndex(
    val packs: List<PackSourceIndex>,
    val archives: List<AssetSourceArchive> = emptyList(),
) {
    private val byPack = packs.associateBy { it.packId }

    val packCount: Int get() = packs.size
    val fileCount: Int get() = packs.sumOf { it.fileCount }

    fun forPack(packId: String): PackSourceIndex? = byPack[packId]

    /** Provenance of one published file, addressed the way ids are: `base:sprites/player.png`. */
    fun provenance(assetId: String): AssetSource? {
        val pack = assetId.substringBefore(':', "")
        val path = assetId.substringAfter(':', assetId)
        val index = byPack[pack] ?: return null
        return index.sourceOf(path)
    }

    fun archiveFor(packId: String): AssetSourceArchive? = archives.firstOrNull { it.packId == packId }

    fun licenses(): List<String> = packs.map { it.license }.filter { it.isNotEmpty() }.distinct().sorted()

    companion object {
        const val INDEX_FILE = "index.json"
        const val ARCHIVE_FILE = "sources.json"
        const val FORMAT = "lumen2d.asset-sources"
        const val ARCHIVE_FORMAT = "lumen2d.asset-source-archive"

        /** Loads every `sources/<pack>/index.json` under [root]. Missing folders are not an error. */
        fun load(vfs: VirtualFileSystem, root: String = ""): AssetSourceIndex {
            val packs = ArrayList<PackSourceIndex>()
            val archives = ArrayList<AssetSourceArchive>()
            val base = root.trimEnd('/')
            val folders = runCatching { vfs.list(base) }.getOrDefault(emptyList())
            for (entry in folders.sorted()) {
                val folder = if (base.isEmpty()) entry else "$base/$entry"
                if (!vfs.isDirectory(folder)) continue
                val indexPath = "$folder/$INDEX_FILE"
                if (vfs.exists(indexPath)) {
                    val data = runCatching { Json.parseObject(vfs.readText(indexPath)) }.getOrNull()
                    if (data != null && data.str("format") == FORMAT) packs.add(PackSourceIndex.fromJson(data))
                }
                val archivePath = "$folder/$ARCHIVE_FILE"
                if (vfs.exists(archivePath)) {
                    val data = runCatching { Json.parseObject(vfs.readText(archivePath)) }.getOrNull()
                    if (data != null && data.str("format") == ARCHIVE_FORMAT) {
                        archives.add(AssetSourceArchive.fromJson(data))
                    }
                }
            }
            // Attach each archive to the pack of the same id when it has one.
            val linked = packs.map { pack ->
                archives.firstOrNull { it.packId == pack.packId }?.let { archive ->
                    PackSourceIndex(pack.packId, pack.name, pack.description, pack.license, pack.author, pack.files, archive)
                } ?: pack
            }
            return AssetSourceIndex(linked, archives)
        }
    }
}

/**
 * `pack.json` — a pack's manifest, as written by the library build and read by the asset browser.
 */
class AssetPackManifest(
    val id: String,
    val name: String,
    val description: String,
    val version: String,
    val license: String,
    val author: String,
    val engine: String,
    val tags: List<String>,
    val files: List<String>,
    /** Folder name of the pack inside the packs root (`base`, `kenney`). */
    val folder: String = id,
    /** Full path the manifest was loaded from (`packs/base`) — empty when built in memory. */
    val root: String = "",
) {
    val fileCount: Int get() = files.size
    fun describe(): String = "$name $version — $license, $fileCount files"

    companion object {
        const val FILE = "pack.json"

        fun fromJson(data: Map<String, Any?>, path: String = ""): AssetPackManifest = AssetPackManifest(
            id = data.str("id").ifEmpty { path.substringAfterLast('/') },
            name = data.str("name").ifEmpty { data.str("id", path.substringAfterLast('/')) },
            description = data.str("description"),
            version = data.str("version", "1.0.0"),
            license = data.str("license"),
            author = data.str("author"),
            engine = data.str("engine"),
            tags = data.strList("tags"),
            files = data.strList("files"),
            folder = path.substringAfterLast('/'),
            root = path,
        )

        /** Loads `<path>/pack.json`; [path] may be empty for a manifest at the root. */
        fun load(vfs: VirtualFileSystem, path: String): AssetPackManifest? {
            val manifestPath = if (path.isEmpty()) FILE else "$path/$FILE"
            if (!vfs.exists(manifestPath)) return null
            val data = runCatching { Json.parseObject(vfs.readText(manifestPath)) }.getOrNull() ?: return null
            return fromJson(data, path)
        }

        /**
         * Finds every pack under [root], sorted by folder. A pack is any folder holding a
         * `pack.json`; folders without one (thumbnails, scratch space) are ignored silently so a
         * user's asset folder can live next to the library.
         */
        fun discover(vfs: VirtualFileSystem, root: String = ""): List<AssetPackManifest> {
            val found = ArrayList<AssetPackManifest>()
            val base = root.trimEnd('/')
            val folders = runCatching { vfs.list(base) }.getOrDefault(emptyList())
            for (entry in folders.sorted()) {
                val folder = if (base.isEmpty()) entry else "$base/$entry"
                if (!vfs.isDirectory(folder)) continue
                load(vfs, folder)?.let { found.add(it) }
            }
            return found
        }
    }
}

/**
 * A pack as the editor sees it: its manifest, its provenance and its place on disk. Loaded in one
 * call by [AssetLibrary.load] so the browser never has to stitch three folders together itself.
 */
class LibraryPack(
    val manifest: AssetPackManifest,
    val sources: PackSourceIndex? = null,
) {
    val id: String get() = manifest.id
    val folder: String get() = manifest.folder
    val name: String get() = manifest.name
    val license: String get() = manifest.license.ifEmpty { sources?.license ?: "" }
    val description: String get() = manifest.description.ifEmpty { sources?.description ?: "" }

    /** Provenance of a file in this pack, by pack-relative path. */
    fun sourceOf(path: String): AssetSource? = sources?.sourceOf(path)

    /** `base:sprites/player.png` — the id the asset database uses for this file. */
    fun assetId(path: String): String = "$id:${path.trimStart('/')}"
}

/** The engine's asset library: every pack under `packs/` with its provenance from `sources/`. */
class AssetLibrary(
    val packs: List<LibraryPack>,
    val index: AssetSourceIndex = AssetSourceIndex(emptyList()),
) {
    private val byId = packs.associateBy { it.id }

    val packCount: Int get() = packs.size
    fun pack(id: String): LibraryPack? = byId[id]
    fun licences(): List<String> = packs.map { it.license }.filter { it.isNotEmpty() }.distinct().sorted()
    fun totalFiles(): Int = packs.sumOf { it.manifest.fileCount }

    /** Packs that came from a third-party archive, with the archive they came from. */
    fun imported(): List<Pair<LibraryPack, AssetSourceArchive>> = packs.mapNotNull { pack ->
        index.archiveFor(pack.id)?.let { pack to it }
    }

    override fun toString(): String =
        "AssetLibrary(${packs.size} packs, ${totalFiles()} files, licences ${licences().joinToString("/")})"

    companion object {
        /** Loads every `packs/…` folder plus `sources/…` from a filesystem that has both folders (e.g. `lib://`). */
        fun load(vfs: VirtualFileSystem, packsRoot: String = "packs", sourcesRoot: String = "sources"): AssetLibrary {
            val index = AssetSourceIndex.load(vfs, sourcesRoot)
            val packs = AssetPackManifest.discover(vfs, packsRoot).map { manifest ->
                LibraryPack(manifest, index.forPack(manifest.id))
            }
            return AssetLibrary(packs, index)
        }
    }
}
