#!/usr/bin/env python3
"""Generate a Kotlin `R` class from an Android `res/` folder.

The Android Gradle plugin generates `R.java` for every resource; without the AGP (offline
type-checking, see tools/typecheck-android.sh) the app sources would not compile. This script walks
`res/values/*.xml` plus the drawable/mipmap/xml folders and writes the same constants.

Usage: tools/generate-r-stub.py <res-dir> <output.kt>
"""
import os
import re
import sys

TYPE_BY_FOLDER = {
    "drawable": "drawable",
    "mipmap": "mipmap",
    "xml": "xml",
    "raw": "raw",
    "layout": "layout",
    "menu": "menu",
    "anim": "anim",
    "values": None,  # handled by the XML parser below
}

# <resources> children that produce id-like constants per name.
VALUE_TAGS = {
    "string": "string",
    "color": "color",
    "dimen": "dimen",
    "bool": "bool",
    "integer": "integer",
    "string-array": "array",
    "integer-array": "array",
    "array": "array",
    "style": "style",
    "plurals": "plurals",
    "attr": "attr",
}


def collect(res_dir):
    entries = {}
    for folder in sorted(os.listdir(res_dir)):
        path = os.path.join(res_dir, folder)
        if not os.path.isdir(path):
            continue
        base = folder.split("-")[0]
        if base not in TYPE_BY_FOLDER:
            continue
        res_type = TYPE_BY_FOLDER[base]
        for name in sorted(os.listdir(path)):
            if name.startswith("."):
                continue
            stem = name.rsplit(".", 1)[0]
            if res_type is None:
                continue
            entries.setdefault(res_type, set()).add(stem.replace(".", "_").replace("-", "_"))
        if base == "values":
            for name in sorted(os.listdir(path)):
                if not name.endswith(".xml"):
                    continue
                text = open(os.path.join(path, name), encoding="utf-8").read()
                for tag, res_type in VALUE_TAGS.items():
                    for match in re.finditer(r"<%s\b[^>]*\bname=\"([^\"]+)\"" % tag, text):
                        entries.setdefault(res_type, set()).add(match.group(1).replace(".", "_"))
    return entries


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    res_dir, out_path = sys.argv[1], sys.argv[2]
    if not os.path.isdir(res_dir):
        print("no res folder at %s — nothing to generate" % res_dir)
        return 1
    entries = collect(res_dir)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    lines = [
        "// Generated by tools/generate-r-stub.py — resource ids for offline type checks.",
        "// The real R class is produced by the Android Gradle plugin; do not edit by hand.",
        "package dev.lumen2d.studio",
        "",
        "object R {",
    ]
    for res_type in sorted(entries):
        names = sorted(entries[res_type])
        if not names:
            continue
        lines.append("    object %s {" % res_type)
        for index, name in enumerate(names, start=1):
            lines.append("        const val %s: Int = 0x7f01%04x" % (name, index))
        lines.append("    }")
    lines.append("}")
    open(out_path, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print("wrote %s (%d resource types)" % (out_path, len(entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
