#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Lumen2D — Android module type check.
#
# Compiles engine-android (and optionally app-android) with kotlinc against the
# hand-written framework declarations in tools/android-stubs, so Android code is
# verified in environments that have no Android SDK. The APK itself is produced
# by Gradle + the SDK (see .github/workflows/android.yml); this script catches
# typos, renamed members and signature mistakes long before a device is involved.
#
# Usage:
#   tools/typecheck-android.sh            # engine-android + app-android
#   tools/typecheck-android.sh engine     # engine-android only
# -----------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOLCHAIN="${LUMEN_TOOLCHAIN:-$HOME/.cache/tools}"
OUT="$ROOT/out"
TARGET="${1:-all}"

export JAVA_HOME="${JAVA_HOME:-$TOOLCHAIN/jdk}"
export PATH="$JAVA_HOME/bin:$TOOLCHAIN/kotlin/bin:$PATH"

if ! command -v kotlinc >/dev/null 2>&1; then
  echo "kotlinc not found. Set LUMEN_TOOLCHAIN to a folder containing jdk/ and kotlin/." >&2
  exit 1
fi

JVM_TARGET="${LUMEN_JVM_TARGET:-17}"
FLAGS=(-jvm-target "$JVM_TARGET" -nowarn)

if [ ! -d "$OUT/classes/core" ]; then
  echo "==> engine-core is not compiled yet; running tools/build-local.sh compile"
  "$ROOT/tools/build-local.sh" compile
fi

echo "==> compiling Android framework stubs"
rm -rf "$OUT/classes/android-stubs"; mkdir -p "$OUT/classes/android-stubs"
kotlinc "${FLAGS[@]}" -d "$OUT/classes/android-stubs" \
  $(find "$ROOT/tools/android-stubs/src" -name '*.kt' | sort)
echo "    ok -> $OUT/classes/android-stubs"

compile_module() {
  local module="$1"
  local out="$OUT/classes/$module"
  echo "==> type-checking $module"
  rm -rf "$out"; mkdir -p "$out"
  kotlinc "${FLAGS[@]}" \
    -classpath "$OUT/classes/core:$OUT/classes/android-stubs" \
    -d "$out" \
    $(find "$ROOT/$module/src/main/kotlin" -name '*.kt' 2>/dev/null | sort)
  echo "    ok -> $out"
}

if [ "$TARGET" = "engine" ] || [ "$TARGET" = "all" ]; then
  compile_module engine-android
fi

if [ "$TARGET" = "app" ] || [ "$TARGET" = "all" ]; then
  # The app module needs an R class. The real one is generated by AGP, so the stand-in is written
  # into out/ (never into src/main, where it would collide with the generated class at build time).
  RES_OUT="$OUT/classes/app-android-res"
  rm -rf "$RES_OUT"; mkdir -p "$RES_OUT"
  echo "==> generating R stub from app resources"
  python3 "$ROOT/tools/generate-r-stub.py" "$ROOT/app-android/src/main/res" "$RES_OUT/R.kt"
  kotlinc "${FLAGS[@]}" \
    -classpath "$OUT/classes/core:$OUT/classes/android-stubs:$OUT/classes/engine-android" \
    -d "$OUT/classes/app-android" \
    $(find "$ROOT/app-android/src/main/kotlin" -name '*.kt' | sort) \
    "$RES_OUT/R.kt"
  echo "    ok -> $OUT/classes/app-android"
fi

echo "Android type check finished."
