/**
 * Asset sources — where the library's bytes come from.
 *
 * A published asset pack is the *output* of the library build; the sources are the *inputs*:
 *
 *  * **generated** sources are engine recipes (`DemoArt.playerSheet()`, `Tone.square(...)`) that
 *    rebuild byte-for-byte identical files, so the pack can be regenerated after any engine change,
 *  * **imported** sources are third-party archives that are vendored under
 *    `assets-library/sources/<pack>/` together with their licence, and republished into the pack by
 *    [KenneyPackBuilder] with metadata and attribution intact.
 *
 * [SourceBook] records one [SourceRecipe] per published file while the pack is built, and writes
 * `sources/index.json` next to a generated `sources/README.md`. That index is what makes the
 * library auditable: opening any file in the library and asking "which recipe made you, and under
 * which licence?" always has an answer, and the answer is produced by the same code that wrote the
 * file, never by hand.
 */
package dev.lumen2d.desktop.demo

import dev.lumen2d.core.math.Rect
import dev.lumen2d.core.render.PngCodec
import dev.lumen2d.core.util.EngineInfo
import dev.lumen2d.core.util.Json
import java.io.File
import java.security.MessageDigest
import java.util.zip.ZipFile

/** How a published library file was produced. */
enum class SourceOrigin(val id: String, val label: String) {
    /** Rebuilt from an engine recipe: art code, tone generator, built-in bitmap font. */
    GENERATED("generated", "Generated by the engine"),

    /** Copied out of a vendored third-party archive. */
    IMPORTED("imported", "Imported from a source archive"),
}

/**
 * One file's provenance.
 *
 * @param path path inside the published pack, e.g. `sprites/player.png` (the pack id lives in the index),
 * @param recipe the exact call that produced it, e.g. `DemoArt.playerSheet()`; for imports this is
 *        the file inside the archive the bytes were copied from,
 * @param source where the input lives: a repository path or a URL,
 * @param importSettings the settings an editor's importer would show (`frameWidth`, `columns`, …).
 */
data class SourceRecipe(
    val path: String,
    val recipe: String,
    val origin: SourceOrigin,
    val source: String,
    val license: String,
    val author: String,
    val importSettings: Map<String, Any?> = emptyMap(),
    val notes: String = "",
) {
    fun toJson(): Map<String, Any?> = linkedMapOf(
        "path" to path,
        "origin" to origin.id,
        "recipe" to recipe,
        "source" to source,
        "license" to license,
        "author" to author,
        "importSettings" to importSettings,
        "notes" to notes,
    )
}

/**
 * Collector for [SourceRecipe]s. Every builder records as it writes, so the source index can never
 * disagree with the files on disk.
 */
class SourceBook(private val root: File, val packId: String, val packName: String,
                val description: String, val license: String, val author: String) {

    private val recipes = ArrayList<SourceRecipe>()

    fun record(recipe: SourceRecipe) { recipes.add(recipe) }

    fun record(path: String, recipe: String, importSettings: Map<String, Any?> = emptyMap(),
               notes: String = "") = record(
        SourceRecipe(
            path = path, recipe = recipe, origin = SourceOrigin.GENERATED,
            source = "engine", license = license, author = author,
            importSettings = importSettings, notes = notes,
        ),
    )

    val size: Int get() = recipes.size
    fun all(): List<SourceRecipe> = recipes

    /** Writes `sources/index.json` (+ a readable `sources/README.md`) for this pack. */
    fun write(): List<String> {
        val directory = File(root, packId)
        directory.mkdirs()
        val index = File(directory, "index.json")
        val payload = linkedMapOf<String, Any?>(
            "format" to "lumen2d.asset-sources",
            "version" to 1,
            "engine" to EngineInfo.VERSION,
            "pack" to packId,
            "name" to packName,
            "description" to description,
            "license" to license,
            "author" to author,
            "fileCount" to recipes.size,
            "files" to recipes.sortedBy { it.path }.map { it.toJson() },
        )
        index.writeText(Json.stringify(payload, pretty = true))
        val readme = File(directory, "README.md")
        readme.writeText(readmeText())
        return listOf(
            root.toPath().relativize(index.toPath()).toString(),
            root.toPath().relativize(readme.toPath()).toString(),
        )
    }

    private fun readmeText(): String {
        val generated = recipes.count { it.origin == SourceOrigin.GENERATED }
        val imported = recipes.count { it.origin == SourceOrigin.IMPORTED }
        val byFolder = recipes.groupBy { it.path.substringBeforeLast('/', "") }
            .toSortedMap()
        return buildString {
            appendLine("# Sources — $packName (`$packId`)")
            appendLine()
            appendLine(description)
            appendLine()
            appendLine("- Licence: **$license**")
            appendLine("- Author: $author")
            appendLine("- Files: ${recipes.size} ($generated generated, $imported imported)")
            appendLine("- Rebuild: `tools/build-local.sh all` or `gradle :engine-desktop:exportAssets`")
            appendLine()
            appendLine("This folder is written by `AssetPackBuilder` from the same code that writes the")
            appendLine("pack, so `index.json` always matches `assets-library/packs/$packId`.")
            appendLine()
            appendLine("| Folder | Files | Recipes |")
            appendLine("| --- | --- | --- |")
            for ((folder, entries) in byFolder) {
                val recipes = entries.map { it.recipe }.distinct().joinToString(", ") { "`$it`" }
                appendLine("| `$folder/` | ${entries.size} | $recipes |")
            }
            appendLine()
            appendLine("## Imported sources")
            appendLine()
            val imports = recipes.filter { it.origin == SourceOrigin.IMPORTED }
            if (imports.isEmpty()) {
                appendLine("None: this pack is fully generated by the engine.")
            } else {
                for (recipe in imports.sortedBy { it.path }) {
                    appendLine("- `${recipe.path}` ← `${recipe.recipe}` (${recipe.source})")
                }
            }
        }
    }
}

/**
 * Imports a third-party archive into the source tree so it can be published as a library pack.
 *
 * The archive is never modified: the few files the engine needs are copied into
 * `assets-library/sources/<pack>/`, described by a `sources.json` (licence, author, tile metrics,
 * SHA-256 of every extracted file). Both files are committed, which is what lets `exportAssets`
 * rebuild the pack on a machine that never sees the original download.
 */
object SourceImporter {

    /** The files a pixel-art tileset archive needs to carry to be publishable as a pack. */
    private val WANTED = listOf(
        "Tilemap/tilemap_packed.png",
        "Tilemap/tilemap-characters_packed.png",
        "Tilesheet (Tiles).txt",
        "Tilesheet (Characters).txt",
        "License.txt",
    )

    /**
     * @param sourcesRoot the `assets-library/sources` folder; [packFolder] is created inside it,
     * @param packId the library pack these bytes get published as (`kenney`), so the archive
     *        descriptor can be linked back to its published pack.
     */
    fun importArchive(archive: File, sourcesRoot: File, packFolder: String = "kenney-pixel-platformer",
                      packId: String = "kenney",
                      displayName: String = "Kenney Pixel Platformer"): List<String> {
        require(archive.isFile) { "no such archive: ${archive.absolutePath}" }
        val target = File(sourcesRoot, packFolder)
        target.mkdirs()
        val written = ArrayList<String>()
        ZipFile(archive).use { zip ->
            for (name in WANTED) {
                val entry = zip.getEntry(name) ?: continue
                val out = File(target, name.substringAfterLast('/'))
                zip.getInputStream(entry).use { input -> out.outputStream().use { input.copyTo(it) } }
                written.add(out.name)
            }
            val licenseText = zip.getEntry("License.txt")?.let { zip.getInputStream(it).readBytes().decodeToString() }
                ?.replace("\r", "")?.trim().orEmpty()
            val sheet = File(target, "tilemap_packed.png")
            val sheetSize = if (sheet.isFile) PngCodec.decode(sheet.readBytes()) else null
            val cells = sheetSize?.let { "${it.width}x${it.height}" } ?: "unknown"
            val columns = if (sheetSize != null) sheetSize.width / 18 else 0
            val rows = if (sheetSize != null) sheetSize.height / 18 else 0
            val payload = linkedMapOf<String, Any?>(
                "format" to "lumen2d.asset-source-archive",
                "version" to 1,
                "id" to packId,
                "packFolder" to packFolder,
                "name" to displayName,
                "upstream" to "https://kenney.nl/assets/pixel-platformer",
                "license" to "CC0-1.0",
                "author" to "Kenney (www.kenney.nl)",
                "archive" to archive.name,
                "archiveSha256" to sha256(archive.readBytes()),
                "tileWidth" to 18,
                "tileHeight" to 18,
                "spacing" to 1,
                "sheetColumns" to columns,
                "sheetRows" to rows,
                "packedSheet" to "tilemap_packed.png",
                "characterSheet" to "tilemap-characters_packed.png",
                "files" to written.sorted().map { name ->
                    val file = File(target, name)
                    linkedMapOf<String, Any?>(
                        "name" to name,
                        "bytes" to file.length(),
                        "sha256" to sha256(file.readBytes()),
                    )
                },
                "licenseText" to licenseText,
            )
            val manifest = File(target, "sources.json")
            manifest.writeText(Json.stringify(payload, pretty = true))
            written.add(manifest.name)
        }
        return written.sorted()
    }

    private fun sha256(bytes: ByteArray): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
        return digest.joinToString("") { "%02x".format(it) }.take(32)
    }
}

/**
 * Publishes a vendored source archive as a library pack.
 *
 * Kenney's pixel-art kit ships an 18×18 tile sheet with a 1 px gutter in the loose files and a
 * *packed* sheet without one; the packed sheet is the one that maps 1:1 onto Lumen2D's tile grid,
 * so it is what the pack publishes (with `columns`/`rows` in the sidecar so the browser can slice
 * it). The loose tiles are still available in the source archive for anyone who wants them.
 */
class KenneyPackBuilder(
    private val packsRoot: File,
    private val sourcesRoot: File,
    private val packId: String = "kenney",
    private val sourceFolder: String = "kenney-pixel-platformer",
) {

    private val written = ArrayList<String>()

    /** Published assets (not sidecars): what `pack.json` lists and the browser shows. */
    private val assets = ArrayList<String>()
    private val book = SourceBook(
        sourcesRoot, packId = packId, packName = "Kenney Pixel Platformer",
        description = "CC0 pixel-art platformer kit (18x18 tiles + characters) imported from the " +
            "vendored Kenney archive.",
        license = "CC0-1.0", author = "Kenney (www.kenney.nl)",
    )

    /** Provenance of an imported file: recorded against the archive entry it came from. */
    private fun imported(path: String, archivePath: String, settings: Map<String, Any?>) {
        book.record(
            SourceRecipe(
                path = path, recipe = archivePath, origin = SourceOrigin.IMPORTED,
                source = "assets-library/sources/$sourceFolder/${archivePath.substringAfterLast('/')}",
                license = "CC0-1.0", author = "Kenney (www.kenney.nl)",
                importSettings = settings,
                notes = "Republished from the vendored archive (see sources.json for hashes).",
            ),
        )
    }

    /** Returns the relative paths of every file written, or an empty list when the source is absent. */
    fun build(): List<String> {
        val source = File(sourcesRoot, sourceFolder)
        val sheet = File(source, "tilemap_packed.png")
        val characters = File(source, "tilemap-characters_packed.png")
        if (!sheet.isFile && !characters.isFile) return emptyList()

        val pack = File(packsRoot, packId)
        val tiles = File(pack, "tiles")
        val sprites = File(pack, "sprites")
        tiles.mkdirs()
        sprites.mkdirs()

        if (sheet.isFile) {
            val buffer = PngCodec.decode(sheet.readBytes())
            val target = File(tiles, "tileset.png")
            target.writeBytes(sheet.readBytes())
            written.add(relative(target))
            assets.add(relative(target).removePrefix("$packId/"))
            val settings = mapOf(
                "tileWidth" to 18, "tileHeight" to 18,
                "columns" to buffer.width / 18, "rows" to buffer.height / 18,
                "spacing" to 0,
                "source" to "Tilemap/tilemap_packed.png",
            )
            note(target, "Tileset (Kenney)", listOf("tileset", "terrain", "kenney"), settings = settings)
            imported("tiles/tileset.png", "Tilemap/tilemap_packed.png", settings)
        }
        if (characters.isFile) {
            val buffer = PngCodec.decode(characters.readBytes())
            val target = File(sprites, "characters.png")
            target.writeBytes(characters.readBytes())
            written.add(relative(target))
            assets.add(relative(target).removePrefix("$packId/"))
            val settings = mapOf(
                "frameWidth" to 18, "frameHeight" to 18,
                "columns" to buffer.width / 18, "rows" to buffer.height / 18,
                "source" to "Tilemap/tilemap-characters_packed.png",
            )
            note(target, "Characters (Kenney)", listOf("character", "kenney"), settings = settings)
            imported("sprites/characters.png", "Tilemap/tilemap-characters_packed.png", settings)
        }

        val manifest = File(pack, "pack.json")
        manifest.writeText(
            Json.stringify(
                linkedMapOf<String, Any?>(
                    "id" to packId,
                    "name" to "Kenney Pixel Platformer",
                    "description" to "CC0 pixel-art platformer kit (18x18 tiles + characters) by Kenney.",
                    "version" to "1.2.0",
                    "license" to "CC0-1.0",
                    "author" to "Kenney (www.kenney.nl)",
                    "engine" to EngineInfo.VERSION,
                    "tags" to listOf("pixel-art", "18x18", "platformer", "cc0"),
                    "files" to assets.sorted(),
                ),
                pretty = true,
            ),
        )
        written.add(relative(manifest))

        val attribution = File(pack, "ATTRIBUTION.md")
        attribution.writeText(
            """
            # Kenney Pixel Platformer (CC0)

            Art by [Kenney](https://kenney.nl/assets/pixel-platformer) — released under
            [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/), which allows commercial use
            without attribution (crediting Kenney is welcome).

            Imported by `SourceImporter` from the vendored archive
            `assets-library/sources/$sourceFolder/`; the extracted files, their SHA-256 hashes and the
            upstream licence text live there. Regenerate this pack with:

            ```
            tools/build-local.sh all          # or: gradle :engine-desktop:exportAssets
            ```
            """.trimIndent() + "\n",
        )
        written.add(relative(attribution))
        written.addAll(book.write())
        return written
    }

    private fun note(file: File, displayName: String, tags: List<String>, settings: Map<String, Any?>) {
        val meta = linkedMapOf<String, Any?>(
            "displayName" to displayName,
            "tags" to tags,
            "license" to "CC0-1.0",
            "author" to "Kenney (www.kenney.nl)",
            "source" to "Kenney Pixel Platformer source archive",
            "sourceUrl" to "https://kenney.nl/assets/pixel-platformer",
            "importSettings" to settings,
        )
        File(file.parentFile, "${file.name}.meta.json").writeText(Json.stringify(meta, pretty = true))
        written.add(relative(File(file.parentFile, "${file.name}.meta.json")))
    }

    private fun relative(file: File): String = packsRoot.toPath().relativize(file.toPath()).toString()
}

/** Nine-patch insets get published in sidecars; kept here so importers use the same shape. */
internal fun nineSliceJson(rect: Rect): List<Float> = listOf(rect.x, rect.y, rect.w, rect.h)
