/**
 * Lumen2D — asset pack builder.
 *
 * Writes the engine's bundled asset library to disk as ordinary, editor-visible files:
 *
 * ```
 * packs/base/
 *   pack.json                 manifest (name, version, license, contents)
 *   sprites/player.png        + player.png.meta.json   (tags, license, import settings)
 *   tiles/tileset.png
 *   ui/panel.png              (nine-patch with insets recorded in the sidecar)
 *   fx/spark.png
 *   fonts/pixel8.png + pixel8.font.json
 *   audio/jump.wav, coin.wav, hurt.wav
 * ```
 *
 * Everything is generated from code, so the library is reproducible, has no third-party licence
 * baggage, and doubles as a demonstration of the engine's own PNG/WAV writers. `lumen2d
 * --export-assets <dir>` runs it; the repo ships the output under `assets-library/packs/base`.
 *
 * Every file is recorded in a [SourceBook] while it is written, so `../sources/base/index.json`
 * documents the exact recipe and licence behind it — see [AssetSources.kt] for the model and for
 * the import path used by packs that come from third-party archives.
 */
package dev.lumen2d.desktop.demo

import dev.lumen2d.core.audio.AudioClip
import dev.lumen2d.core.audio.WavCodec
import dev.lumen2d.core.math.Rect
import dev.lumen2d.core.render.BitmapFont
import dev.lumen2d.core.render.PixelBuffer
import dev.lumen2d.core.render.PixelFont5x7
import dev.lumen2d.core.render.PngCodec
import dev.lumen2d.core.util.Json
import dev.lumen2d.core.util.EngineInfo
import java.io.File
import kotlin.math.PI
import kotlin.math.exp
import kotlin.math.sin

/** Generates the bundled `base` asset pack (and any future packs) into a directory. */
class AssetPackBuilder(
    private val root: File,
    /** Where the provenance index is written; defaults to the `sources/` folder beside `packs/`. */
    private val sourceDirectory: File = File(root.parentFile ?: root, "sources"),
    /** Vendored third-party archives that become packs as well (empty == none available). */
    private val importedPacks: List<String> = defaultImportedPacks(sourceDirectory),
) {

    private val written = ArrayList<String>()

    /** Builds every pack and returns the relative paths of the files written. */
    fun buildAll(): List<String> {
        buildBase()
        for (folder in importedPacks) {
            if (folder == "kenney-pixel-platformer") {
                val files = KenneyPackBuilder(root, sourceDirectory).build()
                written.addAll(files)
            }
        }
        return written
    }

    // ------------------------------------------------------------------------ base pack

    /** The `base` pack: a complete starter kit of 16x16 pixel art, UI, font and sound. */
    fun buildBase(): List<String> {
        val pack = File(root, "base")
        val book = SourceBook(
            sourceDirectory, packId = "base", packName = "Lumen2D Base",
            description = "Starter pixel-art kit generated by the engine: characters, terrain, UI, " +
                "particles, a bitmap font and sound effects.",
            license = "CC0-1.0", author = EngineInfo.AUTHOR,
        )
        val sprites = File(pack, "sprites")
        val tiles = File(pack, "tiles")
        val ui = File(pack, "ui")
        val fx = File(pack, "fx")
        val fonts = File(pack, "fonts")
        val audio = File(pack, "audio")
        listOf(sprites, tiles, ui, fx, fonts, audio).forEach { it.mkdirs() }

        image(File(sprites, "player.png"), DemoArt.playerSheet(), "Player", listOf("character", "player"),
            settings = mapOf("frameWidth" to 16, "frameHeight" to 20, "columns" to 4),
            recipe = "DemoArt.playerSheet()", book = book, notes = "4-frame walk cycle, 16x20")
        image(File(sprites, "slime.png"), DemoArt.slimeSheet(), "Slime", listOf("character", "enemy"),
            settings = mapOf("frameWidth" to 16, "frameHeight" to 16, "columns" to 4),
            recipe = "DemoArt.slimeSheet()", book = book, notes = "4-frame hop cycle, 16x16")
        image(File(sprites, "coin.png"), DemoArt.coinSheet(), "Coin", listOf("pickup", "coin"),
            settings = mapOf("frameWidth" to 12, "frameHeight" to 12, "columns" to 4),
            recipe = "DemoArt.coinSheet()", book = book, notes = "4-frame spin, 12x12")
        image(File(sprites, "flag.png"), DemoArt.flag(), "Goal flag", listOf("level", "goal"),
            recipe = "DemoArt.flag()", book = book)
        image(File(tiles, "tileset.png"), DemoArt.tileSet(), "Terrain tileset", listOf("tileset", "terrain"),
            settings = mapOf("tileWidth" to 16, "tileHeight" to 16, "columns" to 4, "rows" to 3),
            recipe = "DemoArt.tileSet()", book = book, notes = "12 tiles: ground, platform, hazard, decor")
        image(File(ui, "panel.png"), panelNinePatch(), "Panel", listOf("ui", "nine-patch"),
            nineSlice = Rect(6f, 6f, 6f, 6f),
            recipe = "AssetPackBuilder.panelNinePatch()", book = book, notes = "24x24 nine-patch, 6px insets")
        image(File(ui, "button.png"), buttonNinePatch(), "Button", listOf("ui", "nine-patch"),
            nineSlice = Rect(4f, 4f, 4f, 4f),
            recipe = "AssetPackBuilder.buttonNinePatch()", book = book, notes = "16x16 nine-patch, 4px insets")
        image(File(ui, "coin_icon.png"), DemoArt.coinIcon(), "Coin icon", listOf("ui", "icon"),
            recipe = "DemoArt.coinIcon()", book = book)
        image(File(fx, "spark.png"), DemoArt.spark(), "Spark", listOf("fx", "particle"),
            recipe = "DemoArt.spark()", book = book, notes = "soft additive particle")
        image(File(fx, "hills.png"), DemoArt.hills(), "Parallax hills", listOf("background", "parallax"),
            recipe = "DemoArt.hills()", book = book, notes = "seamless 480x120 backdrop")

        builtInFont(File(fonts, "pixel8.png"), File(fonts, "pixel8.font.json"), book)

        sound(File(audio, "jump.wav"), Tone.square(520f, 0.12f, 0.5f, sweep = 900f),
            "Tone.square(520, 0.12, 0.5, sweep=900)", book)
        sound(File(audio, "coin.wav"), Tone.square(880f, 0.14f, 0.4f, sweep = 1760f),
            "Tone.square(880, 0.14, 0.4, sweep=1760)", book)
        sound(File(audio, "hurt.wav"), Tone.noise(0.18f, 0.4f, decay = 12f),
            "Tone.noise(0.18, 0.4, decay=12)", book)
        sound(File(audio, "pickup.wav"), Tone.triangle(660f, 0.1f, 0.45f, sweep = 990f),
            "Tone.triangle(660, 0.1, 0.45, sweep=990)", book)
        sound(File(audio, "blip.wav"), Tone.square(1200f, 0.05f, 0.3f),
            "Tone.square(1200, 0.05, 0.3)", book)

        manifest(
            pack,
            name = "Lumen2D Base",
            description = "Starter pixel-art kit: characters, terrain, UI, particles, font and sound.",
            tags = listOf("pixel-art", "16x16", "starter"),
        )
        written.addAll(book.write())
        return written
    }

    // -------------------------------------------------------------------------- helpers

    private fun image(file: File, buffer: PixelBuffer, displayName: String, tags: List<String>,
                      settings: Map<String, Any?> = emptyMap(), nineSlice: Rect? = null,
                      recipe: String = "", book: SourceBook? = null, notes: String = "") {
        file.parentFile.mkdirs()
        file.writeBytes(PngCodec.encode(buffer))
        note(file, displayName, tags, settings, nineSlice)
        book?.record(
            path = packRelative(file), recipe = recipe,
            importSettings = settings + (nineSlice?.let { mapOf("nineSlice" to nineSliceJson(it)) } ?: emptyMap()),
            notes = notes,
        )
    }

    private fun sound(file: File, clip: AudioClip, recipe: String = "", book: SourceBook? = null) {
        file.parentFile.mkdirs()
        file.writeBytes(WavCodec.encode(clip))
        note(file, file.nameWithoutExtension, listOf("audio", "sfx"))
        book?.record(
            path = packRelative(file), recipe = recipe,
            importSettings = mapOf(
                "sampleRate" to clip.sampleRate, "channels" to clip.channels,
                "seconds" to "%.3f".format(clip.durationSeconds),
            ),
        )
    }

    /** Path of [file] relative to its pack folder (`sprites/player.png`). */
    private fun packRelative(file: File): String {
        val packRoot = file.absoluteFile.parentFile?.parentFile ?: return file.name
        return packRoot.toPath().relativize(file.absoluteFile.toPath()).toString()
    }

    /** Writes the `*.meta.json` sidecar the asset browser reads for tags, licence and import data. */
    private fun note(file: File, displayName: String, tags: List<String>,
                     settings: Map<String, Any?> = emptyMap(), nineSlice: Rect? = null) {
        val meta = linkedMapOf<String, Any?>(
            "displayName" to displayName,
            "tags" to tags,
            "license" to "CC0-1.0",
            "author" to EngineInfo.AUTHOR,
            "source" to "Lumen2D generated asset library",
            "sourceUrl" to "https://github.com/",
        )
        if (settings.isNotEmpty()) meta["importSettings"] = settings
        if (nineSlice != null) meta["nineSlice"] = listOf(nineSlice.x, nineSlice.y, nineSlice.w, nineSlice.h)
        val sidecar = File(file.parentFile, "${file.name}.meta.json")
        sidecar.writeText(Json.stringify(meta, pretty = true))
        written += root.toPath().relativize(file.toPath()).toString()
    }

    private fun builtInFont(atlasFile: File, jsonFile: File, book: SourceBook? = null) {
        val textures = dev.lumen2d.core.render.TextureManager()
        val font = dev.lumen2d.core.render.FontManager.buildPixelFont(textures)
        atlasFile.writeBytes(PngCodec.encode(PixelFont5x7.buildAtlas()))
        jsonFile.writeText(Json.stringify(font.toJsonMap(), pretty = true))
        // Both halves of the font get a sidecar: the browser shows the atlas as an image, and the
        // descriptor as the data that turns it into glyphs.
        note(atlasFile, "Pixel 8 atlas", listOf("font", "bitmap", "atlas"),
            settings = mapOf("size" to 8, "descriptor" to "pixel8.font.json"))
        note(jsonFile, "Pixel 8 font", listOf("font", "bitmap"), settings = mapOf("size" to 8))
        book?.record(
            path = "fonts/pixel8.png", recipe = "FontManager.buildPixelFont() + PixelFont5x7.buildAtlas()",
            importSettings = mapOf("size" to 8, "descriptor" to "pixel8.font.json"),
            notes = "built-in 5x7 bitmap font atlas",
        )
        book?.record(
            path = "fonts/pixel8.font.json", recipe = "BitmapFont.toJsonMap()",
            importSettings = mapOf("atlas" to "pixel8.png"),
        )
    }

    /** 24x24 rounded panel with 6 px insets — the default nine-patch for windows and HUD frames. */
    private fun panelNinePatch(): PixelBuffer {
        val size = 24
        val buffer = PixelBuffer(size, size)
        val fill = 0xFF232A44.toInt()
        val edge = 0xFF3C4670.toInt()
        val highlight = 0xFF4C6EF5.toInt()
        for (y in 0 until size) for (x in 0 until size) {
            val border = x == 0 || y == 0 || x == size - 1 || y == size - 1
            buffer[x, y] = when {
                border -> edge
                x == 1 || y == 1 -> highlight
                else -> fill
            }
        }
        // rounded corners punch out to transparent
        for (corner in listOf(0 to 0, size - 1 to 0, 0 to size - 1, size - 1 to size - 1)) {
            buffer[corner.first, corner.second] = 0
        }
        return buffer
    }

    /** 16x16 button face with 4 px insets. */
    private fun buttonNinePatch(): PixelBuffer {
        val size = 16
        val buffer = PixelBuffer(size, size)
        for (y in 0 until size) for (x in 0 until size) {
            val border = x == 0 || y == 0 || x == size - 1 || y == size - 1
            buffer[x, y] = when {
                border -> 0xFF141721.toInt()
                y == 1 -> 0xFF8FA5FF.toInt()
                else -> 0xFF4C6EF5.toInt()
            }
        }
        return buffer
    }

    private fun manifest(pack: File, name: String, description: String, tags: List<String>) {
        val data = linkedMapOf<String, Any?>(
            "id" to pack.name,
            "name" to name,
            "description" to description,
            "version" to "1.0.0",
            "license" to "CC0-1.0",
            "author" to EngineInfo.AUTHOR,
            "engine" to EngineInfo.VERSION,
            "tags" to tags,
            // Paths are pack-relative (`audio/blip.wav`), never root-relative, so every pack.json
            // in the library reads the same way and can be checked against the pack folder.
            "files" to written.filter { it.startsWith("${pack.name}/") }
                .map { it.removePrefix("${pack.name}/") }
                .sorted(),
        )
        File(pack, "pack.json").writeText(Json.stringify(data, pretty = true))
    }

    companion object {
        /** Imported packs are built only when their vendored source exists (see [SourceImporter]). */
        fun defaultImportedPacks(sourceDirectory: File): List<String> =
            if (File(sourceDirectory, "kenney-pixel-platformer/tilemap_packed.png").isFile)
                listOf("kenney-pixel-platformer") else emptyList()
    }
}

/** Tiny synthesiser used to author the library's sound effects. */
object Tone {

    private const val RATE = 22050

    /** Square-wave beep with an optional pitch sweep. */
    fun square(frequency: Float, seconds: Float, gain: Float, sweep: Float = frequency): AudioClip {
        val frames = (RATE * seconds).toInt()
        val samples = ShortArray(frames)
        var phase = 0.0
        for (i in 0 until frames) {
            val t = i.toFloat() / frames
            val f = frequency + (sweep - frequency) * t
            phase += f / RATE
            val envelope = envelope(t, 0.02f, 0.35f)
            val value = if (phase % 1.0 < 0.5) 1.0 else -1.0
            samples[i] = (value * envelope * gain * 32767).toInt().coerceIn(-32768, 32767).toShort()
        }
        return AudioClip("square", RATE, 1, samples)
    }

    /** Triangle-wave version — softer, good for pickups. */
    fun triangle(frequency: Float, seconds: Float, gain: Float, sweep: Float = frequency): AudioClip {
        val frames = (RATE * seconds).toInt()
        val samples = ShortArray(frames)
        var phase = 0.0
        for (i in 0 until frames) {
            val t = i.toFloat() / frames
            val f = frequency + (sweep - frequency) * t
            phase += f / RATE
            val frac = phase % 1.0
            val value = if (frac < 0.5) frac * 4.0 - 1.0 else 3.0 - frac * 4.0
            samples[i] = (value * envelope(t, 0.01f, 0.4f) * gain * 32767).toInt().coerceIn(-32768, 32767).toShort()
        }
        return AudioClip("triangle", RATE, 1, samples)
    }

    /** Filtered noise burst — impacts, hurt sounds, footsteps. */
    fun noise(seconds: Float, gain: Float, decay: Float = 10f): AudioClip {
        val frames = (RATE * seconds).toInt()
        val samples = ShortArray(frames)
        var seed = 1337
        var last = 0.0
        for (i in 0 until frames) {
            seed = seed * 1103515245 + 12345
            val white = ((seed ushr 16) % 2000) / 1000.0 - 1.0
            last = last * 0.6 + white * 0.4          // simple low-pass
            val t = i.toFloat() / frames
            val value = last * exp(-decay * t) * gain
            samples[i] = (value * 32767).toInt().coerceIn(-32768, 32767).toShort()
        }
        return AudioClip("noise", RATE, 1, samples)
    }

    /** Short attack, exponential release — keeps the synthesised clips click-free. */
    private fun envelope(t: Float, attack: Float, release: Float): Double {
        if (t < attack) return (t / attack).toDouble()
        val r = (t - attack) / (1f - attack)
        return exp(-r / release) * (1.0 - 0.15 * sin(r * PI * 2).let { it * it })
    }
}
