/**
 * Lumen2D — headless preview renderer.
 *
 * Runs the real engine (software renderer, `HeadlessPlatform`) over the demo scenes and writes PNGs
 * plus a markdown index. This is what `tools/build-local.sh preview` and the CI workflow call, so
 * the screenshots in the documentation are always produced by current code rather than hand-made.
 */
package dev.lumen2d.desktop.demo

import dev.lumen2d.core.game.Game
import dev.lumen2d.core.game.GameConfig
import dev.lumen2d.core.game.Project
import dev.lumen2d.core.platform.HeadlessPlatform
import dev.lumen2d.core.platform.InMemoryFileSystem
import dev.lumen2d.core.render.PngCodec
import dev.lumen2d.desktop.installLumenScripts
import java.io.File

/** Renders demo scenes to a directory of PNGs. */
class PreviewGenerator(
    private val output: File,
    private val scale: Int = 1,
) {

    /** Renders one demo; returns the written file, or null when [id] is unknown. */
    fun render(id: String, frames: Int = 24, width: Int = 0, height: Int = 0): File? {
        if (id !in DemoScenes.names) return null
        output.mkdirs()

        val config = GameConfig().also {
            it.title = "Lumen2D · ${id}"
            it.pixelArt = true
            if (width > 0) it.designWidth = width
            if (height > 0) it.designHeight = height
        }
        val project = Project.create(InMemoryFileSystem(), "", config.title, config)
        val game = Game(HeadlessPlatform, project)
        game.useSoftwareRenderer()
        installLumenScripts(game)
        game.start()
        DemoArt.install(game.textures, config.designWidth, config.designHeight)
        DemoScenes.build(id, game)

        // Let the scene settle so particles, tweens and physics show something interesting.
        game.runHeadless(maxOf(frames, DemoScenes.settleFrames(id)))
        val buffer = game.captureFrame() ?: error("Software renderer produced no frame for '$id'")
        val target = File(output, "$id.png")
        target.writeBytes(PngCodec.encode(buffer))
        game.stop()
        return target
    }

    /** Renders every demo plus a markdown index; returns the number of images written. */
    fun renderAll(frames: Int = 24, width: Int = 0, height: Int = 0): List<File> {
        val written = ArrayList<File>()
        val index = StringBuilder("# Lumen2D preview gallery\n\n")
        index.append("Generated by `lumen2d --demo all` from the current engine build.\n\n")
        val stamp = java.time.LocalDate.now().toString()
        index.append("_Last generated: ${stamp}_\n\n")
        for (id in DemoScenes.names) {
            val file = render(id, frames, width, height) ?: continue
            written += file
            index.append("## $id\n\n").append(DemoScenes.describe(id)).append("\n\n")
            index.append("![").append(id).append("](").append(file.name).append(")\n\n")
        }
        File(output, "index.md").writeText(index.toString())
        return written
    }
}
